import 'package:built_collection/built_collection.dart';
import 'package:dr/app_state.dart';
import 'package:dr/middleware/middleware.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test(
      'does not prefetch substitute teacher history after initial setup completed',
      () {
    final state = AppState(
      (b) {
        b.loginState
          ..loggedIn = true
          ..username = 'student';
        b.settingsState
          ..subjectNicksAutoGenerated = true
          ..substitutePrimaryTeachers = MapBuilder<String, BuiltList<String>>({
            'Mathematik': BuiltList<String>(const <String>['Anna Rossi']),
          });
      },
    );

    expect(shouldPrefetchSubstituteTeacherHistory(state), isFalse);
  });
}
