name: dr
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.1.1+4

publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  badges: ^3.1.1
  biometric_storage: ^5.0.1
  built_collection: ^5.1.0
  built_redux:
    path: packages/built_redux
  built_value: ^8.9.2
  charts_flutter:
    path: packages/charts_repo/charts_flutter
  collapsible_sidebar:
    path: packages/collapsible_sidebar/
  collection: ^1.19.1
  cookie_jar: ^4.0.9
  deleteable_tile: ^0.0.1-nullsafety.1
  dio: ^5.9.0
  dio_cookie_manager: ^3.4.0
  flutter:
    sdk: flutter
  flutter_built_redux:
    path: packages/flutter_built_redux
  flutter_colorpicker: ^1.0.3
  flutter_local_notifications: ^17.2.4
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.1.0
  flutter_svg: ^2.2.0
  flutter_widget_from_html_core: ^0.17.0
  fuzzy: ^0.4.0-nullsafety.0
  hive: ^2.0.0
  http: ^1.2.2
  intl: ^0.20.2
  mocktail: ^0.3.0
  mutex: ^3.0.0
  open_file:
    path: packages/open_file
  package_info_plus: ^8.3.1
  path_provider: ^2.1.5
  quill_delta: ^3.0.0-nullsafety.2
  quill_delta_viewer:
    path: packages/quill_delta_viewer/
  responsive_scaffold:
    path: packages/responsive_scaffold/
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.1
  shared_preferences: ^2.5.3
  tuple: ^2.0.0
  uni_links:
    path: packages/uni_links
  url_launcher: ^6.3.2
  workmanager: ^0.9.0+3

dependency_overrides:
  file: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  golden_toolkit: ^0.15.0
  lint: ^2.3.0
  matcher: ^0.12.10-nullsafety.3
  msix: ^3.16.13
  quiver: ^3.2.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/index.png"

flutter_native_splash:
  color: "fafafa"
  color_dark: "303030"
  image: "assets/4.0x/transparent.png"
  image_dark: "assets/4.0x/transparent.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

msix_config:
  display_name: Digitales Register
  publisher_display_name: Michael Debertol
  identity_name: Bucci.DigitalesRegister
  publisher: CN=2508760A-808B-4829-867A-4DB53593750E
  msix_version: 1.1.1.0
  logo_path: assets/4.0x/transparent.png
  architecture: x64
  capabilities: "internetClient"
