import 'package:dr/config.dart';

// Immutable reservations. Never renumber/reuse IDs; rename keys with their schools.
const analyticsSchoolIds = <String, String>{
  "Landesberufsschule für das Gastgewerbe Savoy": "school_0001",
  "Kunstgymnasium und Landesberufsschule Cademia": "school_0002",
  "Cusanus Gymnasium Bruneck": "school_0003",
  "FS Dietenheim": "school_0004",
  "FS Tisens": "school_0005",
  "Fachschule für Land- und Forstwirtschaft Fürstenburg Burgeis": "school_0006",
  "Fachschule für Hauswirtschaft und Ernährung Kortsch": "school_0007",
  "Fachschule Laimburg": "school_0008",
  "Fachschule Neumarkt": "school_0009",
  "Oberschulen J. Ph. Fallmerayer": "school_0010",
  "Fachoberschule für Wirtschaft, Grafik und Kommunikation (TFO/WFO Brixen)":
      "school_0011",
  "FOS Meran": "school_0012",
  "Franziskanergymnasium Bozen": "school_0013",
  "Sozialwissenschaftliches Gymnasium Bruneck": "school_0014",
  "Gymnasien Meran": "school_0015",
  "Gymnasium Walther von der Vogelweide Bozen": "school_0016",
  "Sozialwissenschaftliches Gymnasium JOSEF GASSER Brixen": "school_0017",
  "Herzjesu Institut": "school_0018",
  "WFO Raetia St. Ulrich": "school_0019",
  "Landeshotelfachschule Kaiserhof Meran": "school_0020",
  "GSP Klausen 1": "school_0021",
  "GS Feldthurns": "school_0022",
  "GSS Klausen": "school_0023",
  "Grundschule Kollmann": "school_0024",
  "GS Verdings": "school_0025",
  "Villanders - Grundschulsprengel Klausen 2": "school_0026",
  "GS Waidbruck": "school_0027",
  "LBS Schlanders": "school_0028",
  "LBS Zuegg": "school_0029",
  "LHFS Bruneck": "school_0030",
  "Scores altes La Ila": "school_0031",
  "Mariengarten Zisterzienserinnen-KlosterInternatsschule": "school_0032",
  "Maria Hueber Gymnasium": "school_0033",
  "Mittelschule Klausen": "school_0034",
  "MS Neumarkt & Salurn (Noldin)": "school_0035",
  "Oberschulzentrum Sterzing": "school_0036",
  "OFL Auer": "school_0037",
  "WFO Auer": "school_0038",
  "Realgymnasium und Fachoberschule für Bauwesen „Peter Anich“ Bozen":
      "school_0039",
  "RG/TFO Albert Einstein Meran": "school_0040",
  "SSP Sarntal": "school_0041",
  "GS Kastelruth": "school_0042",
  "GS St. Michael": "school_0043",
  "GS St. Oswald": "school_0044",
  "GS Seis": "school_0045",
  "GS Völs": "school_0046",
  "Mittelschule Schlern (Kastelruth)": "school_0047",
  "Grundschule Moos im Passeier": "school_0048",
  "Grundschule Platt in Passeier": "school_0049",
  "Grundschule Rabenstein in Passeier": "school_0050",
  "Grundschule St. Leonhard": "school_0051",
  "Grundschule Stuls in Passeier": "school_0052",
  "Grundschule Walten in Passeier": "school_0053",
  "SSP St. Leonhard": "school_0054",
  "SSP Mühlbach (Grund- und Mittelschulen)": "school_0055",
  "Grundschulen Sterzing III (Kematen, Mauls, St. Jakob, Stilfes, Trens, Wiesen)":
      "school_0056",
  "SSP Sterzing 3 (Vigil Raber)": "school_0057",
  "Grundschulen SSP Terlan": "school_0058",
  "Mittelschule Terlan": "school_0059",
  "Scola Mesana Selva": "school_0060",
  "Scola elementera Urtijei / Runcadic": "school_0061",
  "Scola mesana Urtijëi": "school_0062",
  "Sozialwissenschaftliches Gymnasium Bozen - Fachoberschule für Tourismus":
      "school_0063",
  "SSP Abtei Scora elementara": "school_0064",
  "Grundschule Ahrntal": "school_0065",
  "Grundschule Luttach / Ahrntal": "school_0066",
  "Grundschule Prettau / Ahrntal": "school_0067",
  "Grundschule Steinhaus / Ahrntal": "school_0068",
  "Grundschule St. Jakob / Ahrntal": "school_0069",
  "Grundschule St. Johann / Ahrntal": "school_0070",
  "Grundschule St. Peter / Ahrntal": "school_0071",
  "Grundschule Weissenbach / Ahrntal": "school_0072",
  "SSP Ahrntal": "school_0073",
  "MS Algund/Partschins": "school_0074",
  "GS Algund": "school_0075",
  "GS Marling": "school_0076",
  "GS Partschins": "school_0077",
  "GS Rabland": "school_0078",
  "Grundschule J. H. Pestalozzi (SSP Bozen Europa)": "school_0079",
  "Grundschule A. Langer (SSP Bozen Europa)": "school_0080",
  "Mittelschule SSP Bozen Europa (Mittelschule A. Schweitzer)": "school_0081",
  "SSP Bruneck 1": "school_0082",
  "Mittelschule Bruneck II": "school_0083",
  "Grundschule Frangart": "school_0084",
  "Grundschule Girlan": "school_0085",
  "Schulsprengel Eppan": "school_0086",
  "Grundschule Gries": "school_0087",
  "Grundschule Innichen": "school_0088",
  "Grundschule Sexten": "school_0089",
  "Grundschule Vierschach": "school_0090",
  "Grundschule Winnebach": "school_0091",
  "SSP Innichen": "school_0092",
  "Mittelschule Blumau (SSP Karneid)": "school_0093",
  "MS Lana": "school_0094",
  "SSP Lana Grundschulen": "school_0095",
  "Grundschule Goldrain": "school_0096",
  "Grundschule Kastelbell": "school_0097",
  "Grundschule Latsch": "school_0098",
  "Grundschule Morter": "school_0099",
  "Grundschule Tarsch": "school_0100",
  "Grundschule Tschars": "school_0101",
  "MS Latsch": "school_0102",
  "GS Branzoll": "school_0103",
  "Grundschule Leifers": "school_0104",
  "GS Pfatten": "school_0105",
  "GS St. Jakob (SSP Leifers)": "school_0106",
  "Mittelschule Leifers": "school_0107",
  "Mittelschule Mals": "school_0108",
  "Grundschulen SSP Mals": "school_0109",
  "Grundschulen SSP Obermais": "school_0110",
  "GS Hafling": "school_0111",
  "SSP Meran Obermais": "school_0112",
  "GS Albert Schweitzer": "school_0113",
  "Grundschule Burgstall": "school_0114",
  "Grundschule Franz Tappeiner": "school_0115",
  "Grundschule Oswald von Wolkenstein Meran": "school_0116",
  "MS Carl Wolf": "school_0117",
  "GS Erckert": "school_0118",
  "SSP Nonsberg Grundschule": "school_0119",
  "SSP Nonsberg Mittelschule": "school_0120",
  "Grundschule Geiselsberg": "school_0121",
  "Grundschule Mittertal": "school_0122",
  "Grundschule Niederolang": "school_0123",
  "Grundschule Niederrasen": "school_0124",
  "Grundschule Niedertal": "school_0125",
  "Grundschule Oberolang": "school_0126",
  "Grundschule Oberrasen": "school_0127",
  "Mittelschule Olang": "school_0128",
  "Schulsprengel Ritten": "school_0129",
  "Grundschulen im SSP Schlanders": "school_0130",
  "Mittelschule Schlanders": "school_0131",
  "Grundschulen SSP Schluderns": "school_0132",
  "Mittelschule Schluderns": "school_0133",
  "Grundschule Saltaus / St. Martin": "school_0134",
  "Grundschule St. Martin": "school_0135",
  "Mittelschule St. Martin": "school_0136",
  "GS Niederdorf": "school_0137",
  "GS Prags": "school_0138",
  "Grundschule Toblach": "school_0139",
  "GS Wahlen": "school_0140",
  "SSP Toblach": "school_0141",
  "Grundschule Tramin": "school_0142",
  "Mittelschule Tramin": "school_0143",
  "Grundschule Afing SSP Tschögglberg": "school_0144",
  "Grundschule Flaas SSP Tschögglberg": "school_0145",
  "Grundschule Jenesien SSP Tschögglberg": "school_0146",
  "Grundschule Mölten SSP Tschögglberg": "school_0147",
  "Grundschule Verschneid SSP Tschögglberg": "school_0148",
  "Grundschule Vöran SSP Tschögglberg": "school_0149",
  "Mittelschule Jenesien": "school_0150",
  "Mittelschule Mölten": "school_0151",
  "Grundschulen im Schulsprengel Ulten": "school_0152",
  "SSP Ulten": "school_0153",
  "Schulsprengel Vintl": "school_0154",
  "Mittelschule Welsberg": "school_0155",
  "Grundschulen Welsberg": "school_0156",
  "Schulsprengel Sterzing I (Grundschulen in Sterzing, Gossensaß und Innerpflersch)":
      "school_0157",
  "GS Ahornach": "school_0158",
  "GS Lappach": "school_0159",
  "GS Mühlwald": "school_0160",
  "GS Rein in Taufers": "school_0161",
  "GS Sand in Taufers": "school_0162",
  "Mittelschule Sand in Taufers": "school_0163",
  "OSZ Sand in Taufers": "school_0164",
  "TFO Bruneck": "school_0165",
  "TFO Bozen": "school_0166",
  "Ursulinen": "school_0167",
  "Vinzentinum": "school_0168",
  "WFO Bozen": "school_0169",
  "WFO Bruneck": "school_0170",
  "WFO Meran": "school_0171",
  "GSP Lana": "school_0172",
  "Grundschulen im Schulsprengel Laas": "school_0173",
  "Mittelschule Laas": "school_0174",
  "Grundschulsprengel Neumarkt": "school_0175",
  "Grundschulsprengel Bozen 1 (Goethe, Chini, Wolff)": "school_0176",
  "Grundschulsprengel Eppan": "school_0177",
  "Grundschule Kaltern": "school_0178",
  "Waldorf WOB Bozen": "school_0179",
  "Mittelschule Kaltern": "school_0180",
  "BBZ Bruneck": "school_0181",
  "Oberbozen (SSP Ritten)": "school_0182",
  "Wangen (SSP Ritten)": "school_0183",
  "GS Lengmoos (SSP Ritten)": "school_0184",
  "GS Oberinn (SSP Ritten)": "school_0185",
  "GS Lengstein (SSP Ritten)": "school_0186",
  "Unterinn (SSP Ritten)": "school_0187",
  "OSZ Schlanders": "school_0188",
  "GS Vinzenz Goller (GSP Brixen)": "school_0189",
  "Mittelschule Oswald von Wolkenstein Brixen": "school_0190",
  "Mittelschule Naturns": "school_0191",
  "Grundschule Marling": "school_0192",
  "Mittelschule Peter Rosegger": "school_0193",
  "Mittelschulen SSP Bozen Stadtzentrum (Aufschnaiter/Egger-Lienz)":
      "school_0194",
  "Grundschule R. Stolz SSP Bozen Stadtzentrum": "school_0195",
  "Grundschule Quirein SSP Bozen Stadtzentrum": "school_0196",
  "Grundschule Partschins": "school_0197",
  "Grundschulen SSP Naturns": "school_0198",
  "MS Tirol": "school_0199",
  "Grunschule Algund": "school_0200",
  "Grundschule Völser Aicha": "school_0201",
  "Mittelschule Gossensaß": "school_0202",
  "Grundschule Steinegg": "school_0203",
  "Grundschule Kardaun": "school_0204",
  "Grundschule Karneid": "school_0205",
  "Grundschule Blumau": "school_0206",
  "Grundschule Tiers": "school_0207",
  "Mittelschule K. Fischnaler": "school_0208",
  "Grundschulen Schulsprengel Sterzing 2": "school_0209",
  "Grundschulen SSP Brixen Milland": "school_0210",
  "Mittelschule Pacher SSP Brixen/Milland": "school_0211",
  "Grundschulsprengel Vahrn": "school_0212",
  "Grundschule Sinich": "school_0213",
  "Grundschule Tirol": "school_0214",
  "Grundschule Deutschnofen": "school_0215",
  "Grundschule Eggen": "school_0216",
  "Grundschule Petersberg": "school_0217",
  "Grundschule Welschnofen": "school_0218",
  "Grundschule Gummer": "school_0219",
  "Mittelschule Deutschnofen": "school_0220",
  "Mittelschule Welschnofen": "school_0221",
  "Grundschule Natz": "school_0222",
  "MS Schenna": "school_0223",
  "MS Prad": "school_0224",
  "GS Prad (Prad, Lichtenberg, Stilfs)": "school_0225",
  "GS Sulden SSP Prad": "school_0226",
  "Scola elementera Sëlva y Scola elementera S. Cristina": "school_0227",
  "SSP Abtei Scuola media \"Tita Alton\"": "school_0228",
  "Mittelschule \"Adalbert Stifter\"": "school_0229",
};

/// A few catalog entries share one register provider URL. Without a persisted
/// school selection distinguishing them, omit association rather than guess.
String? analyticsSchoolIdForUrl(String? url) {
  if (url == null) return null;
  final normalized = url.replaceFirst(RegExp(r'/$'), '');
  final matches =
      schools.entries.where((entry) => entry.value == normalized).toList();
  return matches.length == 1 ? analyticsSchoolIds[matches.single.key] : null;
}
