// Copyright (C) 2021 Michael Debertol
// Copyright (C) 2026 Tobias Bucci
//
// This file is part of digitales_register.
//
// digitales_register is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// digitales_register is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with digitales_register.  If not, see <http://www.gnu.org/licenses/>.

const Map<String, String> schools = {
  "Cusanus Gymnasium Bruneck": "https://cusanus-gymnasium.digitalesregister.it",
  "Fachoberschule für Wirtschaft, Grafik und Kommunikation (TFO/WFO Brixen)": "https://fo-brixen.digitalesregister.it",
  "Fachschule für Hauswirtschaft und Ernährung Kortsch": "https://fs-kortsch.digitalesregister.it",
  "Fachschule für Land- und Forstwirtschaft Fürstenburg Burgeis": "https://fs-fuerstenburg.digitalesregister.it",
  "Fachschule Laimburg": "https://fslaimburg.digitalesregister.it",
  "Fachschule Neumarkt": "https://fachschule-neumarkt.digitalesregister.it",
  "FOS Meran": "https://fos-meran.digitalesregister.it",
  "Franziskanergymnasium Bozen": "https://franziskanergymnasium.digitalesregister.it",
  "FS Dietenheim": "https://fs-dietenheim.digitalesregister.it",
  "FS Tisens": "https://fstisens.digitalesregister.it",
  "Grundschule A. Langer (SSP Bozen Europa)": "https://gs-langer.digitalesregister.it",
  "Grundschule Afing SSP Tschögglberg": "https://gs-afing.digitalesregister.it",
  "Grundschule Ahrntal": "https://gs-ahrntal.digitalesregister.it",
  "Grundschule Barbian": "https://barbian.digitalesregister.it",
  "Grundschule Blumau": "https://gs-blumau.digitalesregister.it",
  "Grundschule Burgstall": "https://gsburgstall.digitalesregister.it",
  "Grundschule Deutschnofen": "https://gs-deutschnofen.digitalesregister.it",
  "Grundschule Eggen": "https://gs-eggen.digitalesregister.it",
  "Grundschule Flaas SSP Tschögglberg": "https://gs-flaas.digitalesregister.it",
  "Grundschule Frangart": "https://gs-frangart.digitalesregister.it",
  "Grundschule Franz Tappeiner": "https://gsfranztappeiner.digitalesregister.it",
  "Grundschule Garn": "https://garn.digitalesregister.it",
  "Grundschule Geiselsberg": "https://gs-geiselsberg.digitalesregister.it",
  "Grundschule Girlan": "https://gs-girlan.digitalesregister.it",
  "Grundschule Goldrain": "https://gs-goldrain.digitalesregister.it",
  "Grundschule Gries": "https://gs-gries.digitalesregister.it",
  "Grundschule Gummer": "https://gs-gummer.digitalesregister.it",
  "Grundschule Innichen": "https://gs-innichen.digitalesregister.it",
  "Grundschule J. H. Pestalozzi (SSP Bozen Europa)": "https://gs-bozeneuropa.digitalesregister.it",
  "Grundschule Jenesien SSP Tschögglberg": "https://gs-jenesien.digitalesregister.it",
  "Grundschule Kaltern": "https://gs-kaltern.digitalesregister.it",
  "Grundschule Kardaun": "https://gs-kardaun.digitalesregister.it",
  "Grundschule Karneid": "https://gs-karneid.digitalesregister.it",
  "Grundschule Kastelbell": "https://gs-kastelbell.digitalesregister.it",
  "Grundschule Kollmann": "https://kollmann.digitalesregister.it",
  "Grundschule Latsch": "https://gs-latsch.digitalesregister.it",
  "Grundschule Latzfons": "https://latzfons.digitalesregister.it",
  "Grundschule Leifers": "https://gs-leifers.digitalesregister.it",
  "Grundschule Luttach / Ahrntal": "https://gs-luttach.digitalesregister.it",
  "Grundschule Marling": "https://gs-marling.digitalesregister.it",
  "Grundschule Mittertal": "https://gs-mittertal.digitalesregister.it",
  "Grundschule Morter": "https://gs-morter.digitalesregister.it",
  "Grundschule Mölten SSP Tschögglberg": "https://gs-moelten.digitalesregister.it",
  "Grundschule Niederolang": "https://gs-niederolang.digitalesregister.it",
  "Grundschule Niederrasen": "https://gs-niederrasen.digitalesregister.it",
  "Grundschule Niedertal": "https://gs-niedertal.digitalesregister.it",
  "Grundschule Oberolang": "https://gs-oberolang.digitalesregister.it",
  "Grundschule Oberrasen": "https://gs-oberrasen.digitalesregister.it",
  "Grundschule Oswald von Wolkenstein Meran": "https://gsoswaldvonwolkenstein.digitalesregister.it",
  "Grundschule Partschins": "https://gs-partschins.digitalesregister.it",
  "Grundschule Petersberg": "https://gs-petersberg.digitalesregister.it",
  "Grundschule Prettau / Ahrntal": "https://gs-prettau.digitalesregister.it",
  "Grundschule Quirein SSP Bozen Stadtzentrum": "https://gs-quirein.digitalesregister.it",
  "Grundschule R. Stolz SSP Bozen Stadtzentrum": "https://gs-bozenstadtzentrum.digitalesregister.it",
  "Grundschule Saltaus / St. Martin": "https://gs-saltaus.digitalesregister.it",
  "Grundschule Sexten": "https://gs-sexten.digitalesregister.it",
  "Grundschule Sinich": "https://gs-sinich.digitalesregister.it",
  "Grundschule St. Jakob / Ahrntal": "https://gs-stjakob.digitalesregister.it",
  "Grundschule St. Johann / Ahrntal": "https://gs-stjohann.digitalesregister.it",
  "Grundschule St. Leonhard": "https://gs-stleonhard.digitalesregister.it",
  "Grundschule St. Martin": "https://gs-stm.digitalesregister.it",
  "Grundschule St. Peter / Ahrntal": "https://gs-stpeter.digitalesregister.it",
  "Grundschule Steinegg": "https://gs-steinegg.digitalesregister.it",
  "Grundschule Steinhaus / Ahrntal": "https://gs-steinhaus.digitalesregister.it",
  "Grundschule Tarsch": "https://gs-tarsch.digitalesregister.it",
  "Grundschule Tiers": "https://gs-tiers.digitalesregister.it",
  "Grundschule Tirol": "https://gs-tirol.digitalesregister.it",
  "Grundschule Toblach": "https://gs-toblach.digitalesregister.it",
  "Grundschule Tramin": "https://gs-tramin.digitalesregister.it",
  "Grundschule Tschars": "https://gs-tschars.digitalesregister.it",
  "Grundschule Vierschach": "https://gs-vierschach.digitalesregister.it",
  "Grundschule Völser Aicha": "https://gs-voelseraicha.digitalesregister.it",
  "Grundschule Vöran SSP Tschögglberg": "https://gs-voeran.digitalesregister.it",
  "Grundschule Weissenbach / Ahrntal": "https://gs-weissenbach.digitalesregister.it",
  "Grundschule Welschnofen": "https://gs-welschnofen.digitalesregister.it",
  "Grundschule Winnebach": "https://gs-winnebach.digitalesregister.it",
  "Grundschulen im Schulsprengel Laas": "https://gs-laas.digitalesregister.it",
  "Grundschulen im Schulsprengel Ulten": "https://gs-ulten.digitalesregister.it",
  "Grundschulen im SSP Schlanders": "https://gs-schlanders.digitalesregister.it",
  "Grundschulen Schulsprengel Sterzing 2": "https://gs-sterzing2.digitalesregister.it",
  "Grundschulen SSP Brixen Milland": "https://gs-brixenmilland.digitalesregister.it",
  "Grundschulen SSP Bruneck1": "https://bruneck1.digitalesregister.it",
  "Grundschulen SSP Mals": "https://sspmals-gs.digitalesregister.it",
  "Grundschulen SSP Naturns": "https://gs-naturns.digitalesregister.it",
  "Grundschulen SSP Obermais": "https://gs-ssp-obermais.digitalesregister.it",
  "Grundschulen SSP Schluderns": "https://gs-schluderns.digitalesregister.it",
  "Grundschulen SSP Terlan": "https://gs-sspterlan.digitalesregister.it",
  "Grundschulen Sterzing III (Kematen, Mauls, St. Jakob, Stilfes, Trens, Wiesen)": "https://gs-sterzing3.digitalesregister.it",
  "Grundschulen Welsberg": "https://ssp-welsberg.digitalesregister.it",
  "Grundschulsprengel Bozen 1 (Goethe, Chini, Wolff)": "https://bozen1.digitalesregister.it",
  "Grundschulsprengel Eppan": "https://gspeppan.digitalesregister.it",
  "Grundschulsprengel Neumarkt": "https://gsp-neumarkt.digitalesregister.it",
  "Grundschulsprengel Vahrn": "https://gsp-vahrn.digitalesregister.it",
  "Grunschule Algund": "https://gs-algund.digitalesregister.it",
  "GS Ahornach": "https://gs-ahornach.digitalesregister.it",
  "GS Albert Schweitzer": "https://gsalbertschweitzer.digitalesregister.it",
  "GS Algund": "https://gs-algund.digitalesregister.it",
  "GS Branzoll": "https://gs-branzoll.digitalesregister.it",
  "GS Erckert": "https://gs-erckert.digitalesregister.it",
  "GS Feldthurns": "https://feldthurns.digitalesregister.it",
  "GS Kastelruth": "https://gs-kastelruth.digitalesregister.it",
  "GS Lappach": "https://gs-lappach.digitalesregister.it",
  "GS Lengmoos (SSP Ritten)": "https://lengmoos.digitalesregister.it",
  "GS Lengstein (SSP Ritten)": "https://lengstein.digitalesregister.it",
  "GS Marling": "https://gs-marling.digitalesregister.it",
  "GS Mühlwald": "https://gs-muehlwald.digitalesregister.it",
  "GS Niederdorf": "https://gs-niederdorf.digitalesregister.it",
  "GS Oberinn (SSP Ritten)": "https://oberinn.digitalesregister.it",
  "GS Partschins": "https://gs-partschins.digitalesregister.it",
  "GS Pfatten": "https://gs-pfatten.digitalesregister.it",
  "GS Planitzing - Schulsprengel Kaltern": "https://gs-planitzing.digitalesregister.it",
  "GS Prad (Prad, Lichtenberg, Stilfs)": "https://gs-prad.digitalesregister.it",
  "GS Prags": "https://gs-prags.digitalesregister.it",
  "GS Rabland": "https://gs-rabland.digitalesregister.it",
  "GS Rein in Taufers": "https://gs-reinintaufers.digitalesregister.it",
  "GS Sand in Taufers": "https://gs-sandintaufers.digitalesregister.it",
  "GS Seis": "https://gs-seis.digitalesregister.it",
  "GS St. Jakob (SSP Leifers)": "https://gs-st-jakob.digitalesregister.it",
  "GS St. Michael": "https://gs-michael.digitalesregister.it",
  "GS St. Oswald": "https://gs-oswald.digitalesregister.it",
  "GS Verdings": "https://verdings.digitalesregister.it",
  "GS Vinzenz Goller (GSP Brixen)": "https://bx-goller.digitalesregister.it",
  "GS Völs": "https://gs-voels.digitalesregister.it",
  "GS Wahlen": "https://gs-wahlen.digitalesregister.it",
  "GS Waidbruck": "https://waidbruck.digitalesregister.it",
  "GSP Klausen 1": "https://klausen1.digitalesregister.it",
  "GSP Lana": "https://gsp-lana.digitalesregister.it",
  "Gymnasien Meran": "https://gymme.digitalesregister.it",
  "Gymnasium Walther von der Vogelweide Bozen": "https://vogelweide.digitalesregister.it",
  "Herzjesu Institut": "https://herzjesu-institut.digitalesregister.it",
  "Kunstgymnasium und Landesberufsschule Cademia": "https://cademia.digitalesregister.it",
  "Landeshotelfachschule Kaiserhof Meran": "https://kaiserhof.digitalesregister.it",
  "LHFS Bruneck": "https://lhfsbruneck.digitalesregister.it",
  "Maria Hueber Gymnasium": "https://mhg.digitalesregister.it",
  "Mariengarten Zisterzienserinnen-KlosterInternatsschule": "https://mariengarten.digitalesregister.it",
  "Mittelschule \"Adalbert Stifter\"": "https://ms-stifter.digitalesregister.it",
  "Mittelschule Blumau (SSP Karneid)": "https://ms-sspkarneid.digitalesregister.it",
  "Mittelschule Bruneck II": "https://meusburger.digitalesregister.it",
  "Mittelschule Deutschnofen": "https://ms-deutschnofen.digitalesregister.it",
  "Mittelschule Gossensaß": "https://ms-goss.digitalesregister.it",
  "Mittelschule Jenesien": "https://ms-jenesien.digitalesregister.it",
  "Mittelschule Kaltern": "https://ms-kaltern.digitalesregister.it",
  "Mittelschule Klausen": "https://ms-klausen.digitalesregister.it",
  "Mittelschule Laas": "https://ms-laas.digitalesregister.it",
  "Mittelschule Leifers": "https://ms-leifers.digitalesregister.it",
  "Mittelschule Mals": "https://ms-mals.digitalesregister.it",
  "Mittelschule Mölten": "https://ms-moelten.digitalesregister.it",
  "Mittelschule Naturns": "https://ms-naturns.digitalesregister.it",
  "Mittelschule Olang": "https://ssp-olang.digitalesregister.it",
  "Mittelschule Oswald von Wolkenstein Brixen": "https://mittelschule-brixen.digitalesregister.it",
  "Mittelschule Pacher SSP Brixen/Milland": "https://ms-brixenmilland.digitalesregister.it",
  "Mittelschule Peter Rosegger": "https://ms-untermais.digitalesregister.it",
  "Mittelschule Sand in Taufers": "https://ms-sand.digitalesregister.it",
  "Mittelschule Schlanders": "https://ms-schlanders.digitalesregister.it",
  "Mittelschule Schlern (Kastelruth)": "https://sspschlern-ms.digitalesregister.it",
  "Mittelschule Schluderns": "https://ms-schluderns.digitalesregister.it",
  "Mittelschule SSP Bozen Europa (Mittelschule A. Schweitzer)": "https://ms-bozeneuropa.digitalesregister.it",
  "Mittelschule St. Martin": "https://ssp-stm.digitalesregister.it",
  "Mittelschule Terlan": "https://ms-sspterlan.digitalesregister.it",
  "Mittelschule Tramin": "https://ssp-tramin.digitalesregister.it",
  "Mittelschule Welsberg": "https://ms-welsberg.digitalesregister.it",
  "Mittelschule Welschnofen": "https://ms-welschnofen.digitalesregister.it",
  "Mittelschulen SSP Bozen Stadtzentrum (Aufschnaiter/Egger-Lienz)": "https://ms-bozenstadtzentrum.digitalesregister.it",
  "MS Algund/Partschins": "https://ms-algund.digitalesregister.it",
  "MS Carl Wolf": "https://mscarlwolf.digitalesregister.it",
  "MS Lana": "https://ssp-lana.digitalesregister.it",
  "MS Latsch": "https://ms-latsch.digitalesregister.it",
  "MS Neumarkt & Salurn (Noldin)": "https://ms-neumarkt.digitalesregister.it",
  "MS Prad": "https://ms-prad.digitalesregister.it",
  "MS Schenna": "https://ms-schenna.digitalesregister.it",
  "MS Tirol": "https://ms-tirol.digitalesregister.it",
  "Oberbozen (SSP Ritten)": "https://oberbozen.digitalesregister.it",
  "Oberschulen J. Ph. Fallmerayer": "https://fallmerayer.digitalesregister.it",
  "Oberschulzentrum Sterzing": "https://osz-sterzing.digitalesregister.it",
  "OFL Auer": "https://oflauer.digitalesregister.it",
  "OSZ Sand in Taufers": "https://sz-sand.digitalesregister.it",
  "OSZ Schlanders": "https://osz-schlanders.digitalesregister.it",
  "Realgymnasium und Fachoberschule für Bauwesen âPeter Anichâ Bozen": "https://rg-fob.digitalesregister.it",
  "RG/TFO Albert Einstein Meran": "https://rgtfo-me.digitalesregister.it",
  "Schulsprengel Eppan": "https://ssp-eppan.digitalesregister.it",
  "Schulsprengel Ritten": "https://ssp-ritten.digitalesregister.it",
  "Schulsprengel Vintl": "https://ssp-vintl.digitalesregister.it",
  "Scola elementera Sëlva y Scola elementera S. Cristina": "https://se-selva.digitalesregister.it",
  "Scola elementera Urtijei / Runcadic": "https://se-urtijei.digitalesregister.it",
  "Scola Mesana Selva": "https://sm-selva.digitalesregister.it",
  "Scola mesana Urtijëi": "https://sm-urtijei.digitalesregister.it",
  "Scores altes La Ila": "https://scoresaltes.digitalesregister.it",
  "Sozialwissenschaftliches Gymnasium Bozen - Fachoberschule für Tourismus": "https://sogym-fotour.digitalesregister.it",
  "Sozialwissenschaftliches Gymnasium Bruneck": "https://sowikunstgym-bruneck.digitalesregister.it",
  "Sozialwissenschaftliches Gymnasium JOSEF GASSER Brixen": "https://gymnasiumbrixen.digitalesregister.it",
  "SSP Abtei Scora elementara": "https://gs-abtei.digitalesregister.it",
  "SSP Abtei Scuola media \"Tita Alton\"": "https://ms-stern.digitalesregister.it",
  "SSP Ahrntal": "https://ssp-ahrntal.digitalesregister.it",
  "SSP Bruneck 1": "https://bruneck1.digitalesregister.it",
  "SSP Innichen": "https://ssp-innichen.digitalesregister.it",
  "SSP Lana Grundschulen": "https://ssplana-gs.digitalesregister.it",
  "SSP Meran Obermais": "https://ssp-meran-obermais.digitalesregister.it",
  "SSP Mühlbach (Grund- und Mittelschulen)": "https://ssp-muehlbach.digitalesregister.it",
  "SSP Nonsberg Grundschule": "https://sspnonsberg-gs.digitalesregister.it",
  "SSP Nonsberg Mittelschule": "https://sspnonsberg-ms.digitalesregister.it",
  "SSP Sarntal": "https://ssp-sarntal.digitalesregister.it",
  "SSP St. Leonhard": "https://ssp-stleonhard.digitalesregister.it",
  "SSP Sterzing 3 (Vigil Raber)": "https://schulsprengel-sterzing3.digitalesregister.it",
  "SSP Toblach": "https://ssp-toblach.digitalesregister.it",
  "SSP Ulten": "https://ssp-ulten.digitalesregister.it",
  "TFO Bozen": "https://tfobz.digitalesregister.it",
  "TFO Bruneck": "https://tfo-bruneck.digitalesregister.it",
  "Unterinn (SSP Ritten)": "https://unterinn.digitalesregister.it",
  "Ursulinen": "https://ursulinen.digitalesregister.it",
  "Villanders - Grundschulsprengel Klausen 2": "https://villanders.digitalesregister.it",
  "Vinzentinum": "https://vinzentinum.digitalesregister.it",
  "Wangen (SSP Ritten)": "https://wangen.digitalesregister.it",
  "WFO Auer": "https://wfoauer.digitalesregister.it",
  "WFO Bozen": "https://wfobz.digitalesregister.it",
  "WFO Bruneck": "https://wfo-bruneck.digitalesregister.it",
  "WFO Meran": "https://wfokafka.digitalesregister.it",
  "WFO Raetia St. Ulrich": "https://ite-raetia.digitalesregister.it",
};
